#+OPTIONS: toc:nil num:nil
#+LaTeX_CLASS: koma-article 
#+LATEX_CLASS_OPTIONS: [letterpaper]

#+LaTex_HEADER: \usepackage{khpreamble}


#+LaTex_HEADER: \addtolength{\oddsidemargin}{-4mm}
#+LaTex_HEADER: \addtolength{\evensidemargin}{-4mm}
#+LaTex_HEADER: \addtolength{\textwidth}{8mm}
#+LaTex_HEADER: \addtolength{\topmargin}{-5mm}
#+LaTex_HEADER: \addtolength{\textheight}{36mm}
#+LaTex_HEADER: \addtolength{\voffset}{-10mm}
#+title: Sampling and anti-aliasing exercise

** The Bessel filter
   A second order Bessel filter
 \[ H(s) = \frac{3}{\big(s/\omega_0\big)^2 + 3\big(s/\omega_0\big) + 3}, \]
 has been designed to give attenuation of 0.1 at a desired Nyquist frequency, i.e. \(|H(i\omega_N)| = 0.1\).

  \begin{center}
  \includegraphics[width=0.8\linewidth]{../../figures/ps7-bessel-bode}
  \end{center}

  1. What is the bandwidth of the filter?
  2. Determine the filter parameter \(\omega_0\) in terms of \(\omega_N\).
  3. What is the phase shift at the Nyquist frequency?
  4. Assume that the cross-over frequency of the loop gain is \(\omega_c = 0.1\omega_N\). What is the phase shift at this frequency?
  5. What delay $T$  does this correspond to if the filter is approximated as a pure delay \(H(i\omega) \approx \mexp{-i\omega T}\)?
  6. How large is the delay in terms of the sampling period \(h = \frac{\pi}{\omega_N}\)?


*** Solution							   :noexport:

    1. The definition of the bandwidth is \(|H(i\omega_B)| = -3db = 0.71\). From the magnitude curve we see that this occurs for \(\omega_B = \approx 0.25\omega_N\)
    2. The equation to use is \(|H(i\omega_N)| = 0.1\) This gives
       \[ |H(i\omega_N)| = \frac{ |3| }{| (i \omega_N/\omega_0)^2 + 3 i \omega_N/\omega_0 + 3|}\]
       Let \( x = (\omega_N/\omega_0)^2\)
       \[ 0.1 = \frac{3}{| (3-x) + i3\sqrt{x}|} \]
       \[ \sqrt{ (3-x)^2 + (3\sqrt{x})^2} = 30 \]
       \[ 9 - 6x + x^2 +  9x = 900 \]
       \[ x^2 +3x -9(100-1) = 0\]
       \[ x = -\frac{3}{2} \pm \frac{1}{2} \sqrt{9 + 4\cdot 9\cdot 99} = -\frac{3}{2}( 1 \pm \sqrt{397}. \]
       Must have positive solution so
       \[\omega_N/\omega_0 = \sqrt{ -\frac{3}{2} (  1 - 19.92 ) } \approx 5.33 \]
       \[ \omega_0 = \omega_N / 5.33 \]
-    3. The minor ticks on the phase curve correspond to 10 degrees. At \(\omega=\omega_N\) we read that \(\arg H(i\omega_N) \approx -148^\circ\)
    4. Same procedure. We get \(\arg H(i 0.1\omega_N) = -30^\circ\)
    5. With \(H(i\omega) \approx \mexp{-i\omega T}\) \(\arg H(i\omega) \approx \arg \mexp{-i\omega T} = -\omega T\) From exerces 2 we had \( -30^\circ = -\frac{\pi}{6} \approx - 0.1\omega_N T\) which gives
       \[ T \approx \frac{10}{6} \cdot \frac{\pi}{\omega_N} = \frac{5}{3} h. \]
    6. See 5+.

\newpage


** Choice of bandwidth of antialiasing filter

#+BEGIN_CENTER 
 \includegraphics[width=0.4\linewidth]{../../figures/Astrom-fig73.png}
#+END_CENTER
   The table can be used to find the delay in the feedback path caused by an antialiasing filter. For instance, if we want to have an attenuation at the Nyquist frequency equal to \(\beta = 0.01\), then a fourth-order Bessel low-pass filter will give a delay of about \(T_d = 3.2 h\), that is a delay of more than 3 sampling periods. 
   1. What is the advantage of using an antialiasing filter of higher order than 2?
   2. If we can only accept a time delay of maximum two sampling periods, what is the attenutation we can obtain at the Nyquist frequency?
   3. If the bandwith frequency of the antialiasing filter is chosen equal to the Nyquist frequency, \(\omega_B = \omega_N\), then by definition of the bandwidth of a filter we have that the attenuation at \(\omega_N\) is 0.7=-3dB. If the sampling period is 0.4 seconds. What is the time delay due to a sixth-order antialiasing filter?
   4. What is the attenuation of a forth-order filter at \(5\omega_B\)

*** Solution							   :noexport:
    1. It will have increased roll-off after the cutoff frequency
    2. 0.1 using a 6th order filter, and between 0.05 and 0.1, using a 4th order filter
    3. The time delay is \(T_d = 0.9h\) so we get 0.36s
    4. This would correspond to the situation \(\omega_N = 5\omega_B\) or \(\omega_B/\omega_N = 0.2\). Line two gives \(\beta=0.01\). One can also reason that a fourth order low-pass filter has a decay of 80dB per decade in the stop band. Since we are asking for the attenuation at half a decade into the stop-band, we should have 40dB attentuation which means 10^{-40/20} = 10^-2 = 0.01.

** Discuss choice of sampling frequency and antialiasing filter
A continuous-time signal $f(t)$ with the Fourier transform $F(\omega)$ given below is to be sampled for the purpose of feedback control. It is known that the signal is corrupted by noise in the form of a sinusoid of frequency $5\omega_0$.

*Discuss the choice of sampling frequency and antialiasing filter*

Hints: 
- There are two alternatives: With antialiasing filter, with no antialiasing filter, but digital low-pass filtering.
- When sampling, the frequencies are "folded" at the Nyquist frequency.

#+BEGIN_CENTER 
\includegraphics[width=0.7\linewidth]{../../figures/choose-sampling-frequency}
#+END_CENTER


*** Solution							   :noexport:
- With antialiasing filter :: In order that the sampling does not give frequency folding that corrupts the signal of interest, we must sample at at least \(\omega_s > 2\omega_0\). The anti-aliasing filter should make sure to filter out the noise. This can be obtained with a notch filter with a notch at \(5\omega_0\). We can also apply a low-pass filter with cutoff frequency at (near) (\omega_0\). A forth-order Bessel filter will then give an attenuation of 0.01 at the noise frequency
- Without antialiasing filter ::  In this case we must sample at a rate so that the alias of the noise frequency does not mix with the frequency of the  interesting signal. It can then be filtered out using a digital filter. Since the frequencies are folded at the Nyquist frequency, we want the Nyquist frequency to be above half-way between \(\omega_0\) and \(5 \omega_0\). This gives \(\omega_N = 3\omega_0\) and \(\omega_s = 6\omega_0\). Then the alias of \(5\omega_0\) will be above \(\omega_0\). 

*NOTE:* IT is actually possible to avoid mixing the alias of the sinusoid by choosing \(\omega_N = 2\omega_0\) since then the sinusoid frequency is folded over to negative frequencies outside the band \(( -\omega_0, \omega_0)\).
