#+OPTIONS: toc:nil num:nil
#+LaTeX_CLASS: koma-article 
#+LaTeX_CLASS_OPTIONS: [letterpaper,fleqn]
#+LaTex_HEADER: \usepackage{khpreamble}
#+LaTex_HEADER: \usepackage{tabularx}
#+LaTex_HEADER: \usepackage{geometry}
#+LaTex_HEADER: \usepackage{pgfplots}
#+LaTex_HEADER: \pgfplotsset{compat=1.13}
#+LaTex_HEADER: \geometry{top=20mm, bottom=20mm, left=24mm, right=18mm}

#+title: Polynomial design exercise
#+date: 

* Determine the order of the controller
#+BEGIN_CENTER 
 \includegraphics[width=0.7\linewidth]{../../figures/2dof-block-explicit}
#+END_CENTER
In each of the cases determine the order of the feedback controller $F_{b}(z)=\frac{S(z)}{R(z)}$ and write out the $R(z)$ and $S(z)$ polynomials. Determine also the order of the observer polynomial $A_o(z)$. You don't have to solve for the controller coefficients.

** Case 1
Plant is \(H(z) = \frac{b_0z+b_1}{z^3  + a_1z^2 + a_2z}\),  desired response to reference signal \(H_c(z) = \frac{0.2^2}{z(z-0.8)(z-0.8)}\), observer poles in the origin.

\vspace*{27mm}

*** Notes							   :noexport:
The diophantine eqn becomes
A(z)R(z) + B(z)S(z) = Ac(z)Ao(z)
The number of eqns it gives is nA+nR.
The controller has no integral action, so the number of unknown coefficients is nR+nR+1. So
nR+NR+1 = nA+nR  => nR = nA-1 = 3-2 = 2.

** Case 2
Plant is \(H(z) = \frac{b_0z+b_1}{z^3  + a_1z^2 + a_2z}\),  desired response to reference signal \(H_c(z) = \frac{0.2^2}{(z-0.8)^3}\), observer poles in the origin and integral action in the feedback controller (incremental controller).


\vspace*{27mm}

*** Notes							   :noexport:
Similar to above, but with integral control. The diophantine eqn becomes
A(z)(z-1)R(z) + B(z)S(z) = Ac(z)Ao(z)
The number of eqns it gives is nA+nR+1.
The controller has integral action, so the number of unknown coefficients is nR+nR+2. So
nR+NR+2 = nA+nR+1  => nR = nA-1 = 3-2 = 2. The controller is R(z) = (z-1)(z^2 + r_1z + r_2) and 
S(z) = s_0z^3 + s_1z^2 + s_2z + s_3.


** Case 3
Plant is \(H(z) = \frac{b_0z+b_1}{z^2  + a_1z + a_2}\) and there is a delay of 2 sampling periods in the feedback path. The desired response to reference signal \(H_c(z) = \frac{0.2^2}{(z-0.8)(z-0.8)}\), observer poles in the origin and integral action in the feedback controller (incremental controller).

*** Notes							   :noexport:
The diophantine eqn becomes
A(z)z^2(z-1)R(z) + B(z)S(z) = Ac(z)Ao(z)
The number of eqns it gives is nA+2+1+nR.
The controller has integral action, so the number of unknown coefficients is nR+nR+2. So
nR+NR+2 = nA+nR+3  => nR = nA + 1 = 2+1 = 3. The controller is R(z) = (z-1)(z^3 + r_1z^2 + r_2z + r_3) and S(z) = s_0z^4 + s_1z^3 + s_2z^2 + s_3z + s_4.
