#+OPTIONS: toc:nil
# #+LaTeX_CLASS: koma-article 

#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation,aspectratio=169]
#+OPTIONS: H:2

#+LaTex_HEADER: \usepackage{khpreamble}
#+LaTex_HEADER: \usepackage{amssymb}
#+LaTex_HEADER: \DeclareMathOperator{\shift}{q}
#+LaTex_HEADER: \DeclareMathOperator{\diff}{p}

#+title: Control computarizado - Asignación de polos, parte 2
# #+date: 2018-08-29

* What do I want the students to understand?			   :noexport:
  - How to design a RST controller

* Which activities will the students do?			   :noexport:
  1. Rank four different pole placements
  2. Determine order of controller in different cases

* Conceptos claves - repetición
** Tres conceptos claves
   1. Dónde poner los polos del sistem en lazo cerrado
   2. La función de /sensibilidad/ y la función de /sensibilidad complementaria/
   3. Determinar el orden del controlador

** Concepto clave 1) Los polos del sistema en lazo cerrado
   #+begin_center
   \includegraphics[height=0.8\textheight]{../../figures/screenshot-2020-07-14.png}
   #+end_center

** Concepto clave 2) Las funciones de sensibilidad y sensibilidad complementaria
** Controlador de dos grados de libertad
#+BEGIN_CENTER 
 \includegraphics[width=0.7\linewidth]{../../figures/2dof-block-explicit}
#+END_CENTER

\begin{align*}
Y(z)     &= \frac{F_f(z)H(z)}{1 + z^{-d}F_b(z)H(z)}U_c(z) + \overbrace{\frac{1}{1 + z^{-d}F_b(z)H(z)}}^{S_s(z)}V(z)  - \overbrace{\frac{z^{-d}F_b(z)H(z)}{1 + z^{-d}F_b(z)H(z)}}^{T_s(z)}N(z)\\
\end{align*}
 
*Evidentemente* \( S_s(z) + T_s(z) = 1\) *Conclusion:* Hay que encontrar un equilibrio entre rechazo a perturbaciones y rechazo a ruido de medida.

** Sensibilidad y sensibilidad complementaria
#+begin_center
\includegraphics[width=0.7\linewidth]{../matlab/bode-sensitivity-exercise-crop}
#+end_center

*** Notas                                                          :noexport:
Según la relación S_s(z) + T_s(z) = 1, sabemos que no vamos a poder tener rechazo bueno a perturbaciones y rechazo bueno a ruido de medida en el mismo rango de frecuencias. Si S_s(z) \approx 0 para ciertas frecuencias, entonces T_s(z) \approx 1, y ruido pasa sin rechazo a la salida.
Pero es tambien nos dice la relación que si S_s(z) es grande >> 1, entonces T_s(z) >> 1 tambien. Es decir por frecuencias donde tenemos mucha sensibilidad (amplificación) a perturbaciones vamos a tambien tener sensibildad (amplificación) a ruido de medida. 


** Sensibilidad y sensibilidad complementaria -  Solución
    \pgfmathsetmacro{\Smag}{0.12}
    \pgfmathsetmacro{\Sarg}{70}
    \pgfmathsetmacro{\Tmag}{0.98}
    \pgfmathsetmacro{\Targ}{-6}
    \pgfmathsetmacro{\Treal}{\Tmag*cos(\Targ)}
    \pgfmathsetmacro{\Tim}{\Tmag*sin(\Targ)}

    \pgfmathsetmacro{\Smagtwo}{0.12}
    \pgfmathsetmacro{\Sargtwo}{70}
    \pgfmathsetmacro{\Srealtwo}{\Smagtwo*cos(\Sargtwo)}
    \pgfmathsetmacro{\Simtwo}{\Smag*sin(\Sarg)}
    \pgfmathsetmacro{\Tmagtwo}{0.98}
    \pgfmathsetmacro{\Targtwo}{-6}

#+begin_export latex
\begin{center}
  \begin{tikzpicture}[scale=1.6]

    \draw[->] (-2, 0) -- (2, 0) node[below] {Re};
    \draw[->] (0,-2) -- (0,2) node[left] {Im};
    \draw (1,0) -- (1,-0.05) node[below] {1};
    \draw (-1,0) -- (-1,-0.05) node[below] {-1};
    \draw (0,1) -- (-0.05,1) node[left] {i};
    \draw (0,-1) -- (-0.05,-1) node[left] {-i};
 

    \foreach \Tmag/\Targ/\nn in {-0.149/-6/1, 3.44/-88/2, -19/-196/3} {
       \pgfmathsetmacro{\Treal}{pow(10,\Tmag/20)*cos(\Targ)}
       \pgfmathsetmacro{\Tim}{pow(10,\Tmag/20)*sin(\Targ)}
       \node[circle, fill, orange, inner sep= 1pt] (Tone) at (\Treal, \Tim) {};
           \draw[thin, ->, orange] (0,0) to (Tone) node[right] {\tiny \nn};
	   }
    \foreach \Smag/\Sarg/\nn in {-18/78/1, 4.9/57/2, 0.85/-1.67/3} {
       \pgfmathsetmacro{\Sreal}{pow(10,\Smag/20)*cos(\Sarg)}
       \pgfmathsetmacro{\Sim}{pow(10,\Smag/20)*sin(\Sarg)}
       \node[circle, fill, blue!80, inner sep= 1pt] (Sone) at (\Sreal, \Sim) {};
           \draw[thin, ->, blue!80] (0,0) to (Sone) node[right] {\tiny \nn};
	   }

    %\node[circle, fill, blue!80, inner sep= 1pt] (Sone) at (\Sreal, \Sim) {};
    %\draw[thin, ->, blue!80] (0,0) to (Sone);
  \end{tikzpicture}
\end{center}
#+end_export


** La función de sensibilidad

   \[S_s(z) = \frac{1}{1 + z^{-d}F_b(z)H(z)} = \frac{1}{1 + G_o(z)}= \frac{1}{G_o(z) - (-1)}\]


*** Text
    :PROPERTIES:
    :BEAMER_col: 0.45
    :END:

   \[|S_s(\mathrm{e}^{i\omega h})| = |S_s(i\omega)| = \frac{1}{| G_o(i\omega) - (-1)|}\]

    *La magntiúd de la función de sensibilidad es inversa proporcional  a la distancia de la curva de Nyquist al punto critico -1*

*** Graphics
    :PROPERTIES:
    :BEAMER_col: 0.65
    :END:
    #+begin_center
    \includegraphics[width=0.6\linewidth]{../../figures/implane-nyquist-margins}
    #+end_center

** La función de sensibilidad - ejercicio
*Actividad* Dibuja la magnitúd de la funcion de sensibilidad, dado la curva de Nyquist.

*** Bode
    :PROPERTIES:
    :BEAMER_col: 0.65
    :END:

    #+begin_export latex
	\begin{center}
	\begin{tikzpicture}
      \begin{loglogaxis} [
          clip=false,
	  ylabel=$|S_s(i\omega)|$,
	  width=9cm,
	  height=5cm,
	  %grid=both,
	  ytick={0.1, 1, 10},
	  xticklabel=\empty,
	  ymin=0.1, ymax=10,
	  xmin=0.1, xmax=10,
	  every major grid/.style={red, opacity=0.5},
	  %legend entries={Bessel filter, Delay of one},
	  %legend pos={south west},
      ]
     %   \addplot 
     %   shell[thick,black, no marks, prefix=pgfshell_, id=bodenm,] {julia -q --eval  "G=tf([3],[(1.0/\omegazero)^2, 3/\omegazero, 3]); print_bode_phase(G, -2, 2);"};
     \draw[orange!90!black] (axis cs: 1, 0.13) -- (axis cs: 1, 0.1) node[below] {$\omega_c$};
     \draw[orange!90!black] (axis cs: 3, 0.13) -- (axis cs: 3, 0.1) node[below] {$\omega_p$};
      \end{loglogaxis}
    \end{tikzpicture}
    \end{center}
    #+end_export


*** Graphics
    :PROPERTIES:
    :BEAMER_col: 0.35
    :END:
    #+begin_center
    \includegraphics[width=0.99\linewidth]{../../figures/implane-nyquist-margins}
    #+end_center

** La función de sensibilidad - solución

*** Bode
    :PROPERTIES:
    :BEAMER_col: 0.65
    :END:

    #+begin_export latex
	\begin{center}
	\begin{tikzpicture}
      \begin{loglogaxis} [
          clip=false,
	  ylabel=$|S_s(i\omega)|$,
	  width=9cm,
	  height=5cm,
	  %grid=both,
	  ytick={0.1, 1, 10},
	  xticklabel=\empty,
	  ymin=0.1, ymax=10,
	  xmin=0.1, xmax=10,
	  every major grid/.style={red, opacity=0.5},
	  %legend entries={Bessel filter, Delay of one},
	  %legend pos={south west},
      ]
        \addplot[thick, red!80!black, no marks, smooth] coordinates {(0.1, 0.1) (1, 1.1) (2, 1.6) (3, 1.49) (10,1) };
     \draw[orange!90!black] (axis cs: 1, 0.13) -- (axis cs: 1, 0.1) node[below] {$\omega_c$};
     \draw[orange!90!black] (axis cs: 3, 0.13) -- (axis cs: 3, 0.1) node[below] {$\omega_p$};
      \end{loglogaxis}
    \end{tikzpicture}
    \end{center}
    #+end_export


*** Graphics
    :PROPERTIES:
    :BEAMER_col: 0.35
    :END:
    #+begin_center
    \includegraphics[width=0.99\linewidth]{../../figures/implane-nyquist-margins}
    #+end_center

   
* Cancelación de polos del observador
** Controlador de dos grados de libertad
#+BEGIN_CENTER 
 \includegraphics[width=0.7\linewidth]{../../figures/2dof-block-explicit}
#+END_CENTER

\begin{align*}
Y(z) &= \frac{T(z)B(z)z^d}{z^dA(z)R(z) + B(z)S(z)}U_c(z) + \frac{A(z)R(z)z^d}{z^dA(z)R(z) + B(z)S(z)}V(z)\\ & \qquad\qquad\qquad - \frac{S(z)B(z)}{z^dA(z)R(z) + B(z)S(z)}N(z)
\end{align*}
 
** Controlador de dos grados de libertad
#+BEGIN_CENTER 
 \includegraphics[width=0.7\linewidth]{../../figures/2dof-block-explicit}
#+END_CENTER
\begin{align*}
Y(z) &= \frac{t_0B(z)z^d}{A_c(z)}U_c(z) + \frac{A(z)R(z)z^d}{A_c(z)A_o(z)}V(z)- \frac{S(z)B(z)}{A_c(z)A_o(z)}N(z)
\end{align*}
 *Conclusiones* 1) Hay una separación parcial entre seguimiento de la referencia y rechazo a perturbaciones. 2) Se puede usar los polos correspondientes a las raíces de \(A_o(z)\) para afinar el rechazo a perturbaciones contra rechazo a ruido de medida. 


* RST

** Procedimiento - asignación de polos
   Dado modelo del proceso \(H(z)=\frac{B(z)}{A(z)}\), y especificaciones de polos deseados del sistema en lazo cerrado \(A_{cl}(z) = (z-\alpha_1)(z-\alpha_2) \cdots (z-\alpha_{n_c})\)
   1. Determina la ecuación diofantina
      \[ A(z)R(z)z^{d} + B(z)S(z) = A_{cl}(z) \]
      y el orden adecuado del controlador, con \(\deg S = \deg R\).
   2. Factoriza el polinomio caracteristico del lazo cerrado \(A_{cl}(z) = A_c(z)A_o(z)\), donde \(n_{A_o} = n_R\). 
   3. Determina polinomios \(R(z)\) y \(S(z)\) que satisfican
      \[ A(z)R(z)z^{d} + B(z)S(z) = A_{cl}(z) \]

** Procedimiento
   Dado modelo del proceso \(H(z)=\frac{B(z)}{A(z)}\), y especificaciones de polos deseados del sistema en lazo cerrado \(A_{cl}(z) = (z-\alpha_1)(z-\alpha_2) \cdots (z-\alpha_{n_c})\)
   4. [@4] Elige
      \[T(z) = t_0 A_o(z),\] donde \(t_0 = \frac{A_c(1)}{B(1)}\).

   Obtenemos la *ley de control* 
   \[ R(q) u(k) = T(q)u_c(k) - S(q)y(k). \]
   y la respuesta en lazo cerrado a la señal de referencia
   \[ y(k) = \frac{t_0 B(q)}{A_c(q)} u_c(k). \]

** Concepto clave 3) Determinando el orden del controlador
   Tenemos la ecuación diofantina
      \[ A(z)R(z)z^{d} + B(z)S(z) = A_{cl}(z) \qquad (*) \]
   y el controlador
   \[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^n + s_1z^{n-1} + \cdots + s_n}{z^n + r_1 z^{n-1} + \cdots + r_n}\]
   *¿Cómo decidir el orden del controlador?* Nota
   - el controlador tiene $n+n+1 = 2\deg R + 1$ parámetros desconocidos
   - el lado izquierdo de \((*)\) tiene el grado $\deg \big(A(z)R(z)z^d + B(z)S(z)\big) = \deg A + \deg R + d$
   - la ecuación diofantina da un numero de ecuaciones (no-triviales) igual a su grado, al poner iguales los coeficientes correspondientes de los dos lados.

     *\(\Rightarrow\;\)Elige \(\deg R\) que satisface \(2\deg R + 1 = \deg A + \deg R + d\)*
     

* Ejemplo
** Ejemplo - Control de nivel de una presa
#+BEGIN_CENTER 
 \includegraphics[width=0.5\linewidth]{../../figures/kraftverk}
#+END_CENTER

*Objetivo* Obtener un sistema en lazo cerrado con polos en \(z=0.9\).

** Ejemplo - Control de nivel de una presa
#+BEGIN_CENTER 
 \includegraphics[width=0.3\linewidth]{../../figures/kraftverk}
#+END_CENTER

*Dinámica del proceso*

    #+begin_export latex
    \begin{center}
      \begin{tikzpicture}
	\node at (0,0) {$y(k) = y(k-1) -v(k-1) + u(k-2)$};
	\node[coordinate, pin=140:{Cambio en el nivel de agua}] at (-2.6,0.2) {};
	\node[coordinate, pin=-140:{Cambio en flujos no controlados}] at (0.8,-0.2) {};
	\node[coordinate, pin=60:{Cambio en flujo controlado}] at (2,0.2) {};
    \end{tikzpicture}
    \end{center}
    \begin{center}
      \begin{tikzpicture}[node distance=22mm, block/.style={rectangle, draw, minimum width=15mm}, sumnode/.style={circle, draw, inner sep=2pt}]
    
	\node[coordinate] (input) {};
	\node[block, right of=input, node distance=20mm] (delay)  {$z^{-1}$};
	\node[sumnode, right of=delay, node distance=16mm] (sum) {\tiny $\Sigma$};
	\node[block, right of=sum, node distance=20mm] (plant)  {$H_p(z)$};
	\node[coordinate, above of=sum, node distance=12mm] (disturbance) {};
	\node[coordinate, right of=plant, node distance=20mm] (output) {};

	\draw[->] (input) -- node[above, pos=0.3] {$u(k)$} (delay);
	\draw[->] (sum) -- node[above] {} (plant);
	\draw[->] (plant) -- node[above, near end] {$y(k)$} (output);
	\draw[->] (disturbance) -- node[right, pos=0.2] {$v(k)$} node[left, pos=0.8] {$-$} (sum);
	\draw[->] (delay) -- (sum);
      \end{tikzpicture}
    \end{center}
    #+end_export

** Ejemplo - Control de nivel de una presa

*Dinámica del proceso*

    #+begin_export latex
    \begin{center}
      \begin{tikzpicture}
	\node at (0,0) {$y(k) = y(k-1) -v(k-1) + u(k-2)$};
	\node[coordinate, pin=140:{Cambio en el nivel de agua}] at (-2.6,0.2) {};
	\node[coordinate, pin=-140:{Cambio en flujos no controlados}] at (0.8,-0.2) {};
	\node[coordinate, pin=60:{Cambio en flujo controlado}] at (2,0.2) {};
    \end{tikzpicture}
    \end{center}
    \begin{center}
      \begin{tikzpicture}[node distance=22mm, block/.style={rectangle, draw, minimum width=15mm}, sumnode/.style={circle, draw, inner sep=2pt}]
    
	\node[coordinate] (input) {};
	\node[block, right of=input, node distance=20mm] (delay)  {$z^{-1}$};
	\node[sumnode, right of=delay, node distance=16mm] (sum) {\tiny $\Sigma$};
	\node[block, right of=sum, node distance=20mm] (plant)  {$H_p(z)$};
	\node[coordinate, above of=sum, node distance=12mm] (disturbance) {};
	\node[coordinate, right of=plant, node distance=20mm] (output) {};

	\draw[->] (input) -- node[above, pos=0.3] {$u(k)$} (delay);
	\draw[->] (sum) -- node[above] {} (plant);
	\draw[->] (plant) -- node[above, near end] {$y(k)$} (output);
	\draw[->] (disturbance) -- node[right, pos=0.2] {$v(k)$} node[left, pos=0.8] {$-$} (sum);
	\draw[->] (delay) -- (sum);
      \end{tikzpicture}
    \end{center}
    #+end_export
*Actividad* ¿Cuál es la funcion de transferencia de $u(k)$ a $y(k)$?

|1: \(H(z) = \frac{z}{z-1}\) | 2: \(H(z)=\frac{1}{z-1} \) | 3: \(H(z)=\frac{1}{z(z-1)}\) |


** Ejemplo - Control de nivel de una presa
   Dado proceso \(H(z) = \frac{B(z)}{A(z)} = \frac{1}{z(z-1)}\) y polos deseados en \(z=0.9\).
   
  1. Ecuación diofantina \(A(z)R(z)z^d + B(z)S(z) = A_{cl}(z)\)
     \[ z(z-1)R(z) + S(z) = A_{cl}(z)\]
     El orden del controlador es 
     \[\deg R = \deg A + d - 1 = 2-1 = 1, \quad \Rightarrow \quad F_b(z)=\frac{S(z)}{R(z)} = \frac{s_0z + s_1}{z + r_1}\]
  2. Tenemos la ecuación diofantina
     \[ z(z-1)(z+r_1) + s_0z + s_1 = A_{cl}(z)\]
     El grado de \(A_{cl}(z)\) es 3. Eligimos \(A_o(z) = z\),  ( \(\deg A_o = \deg R\)) 
     \[ A_{cl}(z) = A_o(z) A_c(z) = z(z-0.9)^2\]

** Ejemplo - Control de nivel de una presa
  3. [@3] De la ecuación diofantina \[ z(z-1)(z+r_1) + s_0z + s_1 = z(z-0.9)^2\]
     \[ z^3 + (r_1-1)z^2 - r_1z + s_0z + s_1 = z^3 -1.8z^2 + 0.81z\]
     Obtenemos las ecuaciones 
     \begin{align*}
     \begin{cases} z^2 &: \quad r_1-1 = -1.8\\
     z^1 &: \quad -r_1 + s_0 = 0.81\\
     z^0 &: \quad s_1 = 0
     \end{cases}
     \quad \Rightarrow \quad 
     \begin{cases} r_1 &= -0.8\\ s_0 &= 0.01\\ s_1 &=0 \end{cases}
     \end{align*}
     \[F_b(z) = \frac{0.01z}{z - 0.8}\]

** Ejemplo - Control de nivel de una presa
  4. [@4] Tenemos \(A_o(z) = z\), entonces 
     \[T(z) = t_0A_o(z) = t_0z\]
     \[G_c(z) = \frac{T(z)B(z)}{A_o(z)A_c(z)} = \frac{t_0 B(z)}{A_c(z)}, \quad \text{queremos}\, G_c(1)=1\]
     \[ t_0 = \frac{A_c(1)}{B(1)} = \frac{(1-0.9)^2}{1} = 0.01\]

  *Ley de control*
  \[R(\shift) u(kh) = T(\shift)u_c(kh) - S(\shift)y(kh)\]
  \[ (\shift - 0.8)u(kh) = 0.01\shift u_c(kh) - 0.01\shift y(kh)\]
  \[ u(kh+h) = 0.8u(kh) + 0.01 u_c(kh+h) - 0.01y(kh+h)\]

*** Notes							   :noexport:
    - x is change in level of water in the dam from some operating point Volume = Volume_0 + x
    - u is change in flow through dam gates from some operating point. 
    - v is change in flow out. Either through increase in flow through power dam or decrease in river  
      d/dt Vol =  d/dt (Vol_0 + x(t)) = flow in - flow out
               = n_0 - v_0 - v(t) - u_0 + u(t), with n_0 - v_0 - u_0 = 0   
      dx/dt = u - v. 

    - Model  X = \frac{z}{z-1} (U-V) 

    - H(z) = B(z)/A(z) = z/(z-1). 

    - Diophantine eqn
      AR + BS = Ac
      (z-1)R + zS = Ac
      With first-order controller S/R = (s0z + s1)/(z + r1)
      (z-1)(z+r1) + z(s0z + s1) = (z-0.7)^2 , Ac = Acl = (z-0.7)^2 
      or Ac = Acl Ao = (z-0.7)(z-a) 

      (z-1)(z+r1) + s0z^2 + s1z = (z-0.7)(z-a)
      z^2 - (1-r1)z -r1  + s0z^2 + s1z = z^2 - (0.7+a)z + 0.7*a.
      z^2: 1 + s0 = 1   => s0=0
      z^1: -(1-r1) + s1 = -(0.7+a)
      z^0: -r1 = 0.7a

      
      r1s0s1 = [0, 1, 0; 1, 0, 1; -1, 0, 0]\[1; -0.7-a; 0.7*a] 


      (-2+s0) = -0.7-a => s0 = 1.3-a
      s1 = 0.7*a - 1

      We have Gc = T/R B/A / (1 + S/R B/A) = TB / (AR + BS) = TB / (Ao Ac)
      Let T = Ao*t_0
      Gc = t_0 B / Ac, Want Gc(1) = 1 
      t_0 = Ac(1) / B(1) = (1-0.7)/1 = 0.3.


      Try 
      

* Ejercicios
** Ejercicios
** Concepto clave 3) Determinando el orden del controlador
   Tenemos la ecuación diafóntica
      \[ A(z)R(z)z^{d} + B(z)S(z) = A_{cl}(z) \qquad (*) \]
   y el controlador de retroalimentación
   \[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^n + s_1z^{n-1} + \cdots + s_n}{z^n + r_1 z^{n-1} + \cdots + r_n}\]
   *¿Cómo decidir el orden del controlador?* Nota
   - el controlador tiene $n+n+1 = 2\deg R + 1$ parámetros desconocidos
   - el lado izquierdo de \((*)\) tiene el grado $\deg \big(A(z)R(z)z^d + B(z)S(z)\big) = \deg A + \deg R + d$
   - la ecuación diofantina nos un numero de ecuaciones (no-triviales) igual a su grado, al poner coeficientes de los dos lados iguales.

     *\(\Rightarrow\;\)Elige \(\deg R\) que satisface \(2\deg R + 1 = \deg A + \deg R + d\)*
     
** Determinando el orden del controlador - Ejercicio 1
   Recuerda    *\(\Rightarrow\;\)Elige \(\deg R\) que satisface \(2\deg R + 1 = \deg A + \deg R + d\)*

   Dado modelo del proceso \[H(z) = \frac{B(z)}{A(z)} = \frac{b}{z + a}\] y \(d=0\) (ningun retraso en el lazo) ¿Cuál es el orden apropiado del controlador 
\[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^n + s_1z^{n-1} + \cdots + s_n}{z^n + r_1 z^{n-1} + \cdots + r_n}\]
para que se puede determinar todos los parametros usando la ecuación diofantina

   \[ A(z)R(z) + B(z)S(z) = A_c(z)A_o(z)?\]
   | 1. \(n = 0\) | 2. \(n = 1\) |
   | 3. \(n=2\)   | 4. \(n=3\)   |

** Determinando el orden del controlador - Ejercicio 1, Solución
   Recuerda    *\(\Rightarrow\;\)Elige \(\deg R\) que satisface \(2\deg R + 1 = \deg A + \deg R + d\)*

   Dado modelo del proceso \[H(z) = \frac{B(z)}{A(z)} = \frac{b}{z + a}\] y \(d=0\) (ningun retraso en el lazo) ¿Cuál es el orden apropiado del controlador 
\[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^n + s_1z^{n-1} + \cdots + s_n}{z^n + r_1 z^{n-1} + \cdots + r_n}\]
para que se puede determinar todos los parametros usando la ecuación diofantina

   \[ A(z)R(z) + B(z)S(z) = A_c(z)A_o(z)?\]
   | 1. \(n = 0\) | 2. \(n = 1\) |
   | 3. \(n=2\)   | 4. \(n=3\)   |

** Determinando el orden del controlador - Ejercicio 2
   Recuerda    *\(\Rightarrow\;\)Elige \(\deg R\) que satisface \(2\deg R + 1 = \deg A + \deg R + d\)*

   Dado modelo del proceso \[H(z) = \frac{B(z)}{A(z)} = \frac{b_0z + b_1}{z^2 + a_1z + a_2}\] y \(d=2\)  ¿Cuál es el orden apropiado del controlador 
\[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^n + s_1z^{n-1} + \cdots + s_n}{z^n + r_1 z^{n-1} + \cdots + r_n}\]
para que se puede determinar todos los parametros usando la ecuación diofantina

   \[ A(z)R(z) + B(z)S(z) = A_c(z)A_o(z)?\]

  | 1. \(n = 1\) | 2. \(n = 2\) |
   | 3. \(n=3\)   | 4. \(n=4\)   |

** Determinando el orden del controlador - Ejercicio 2, Solución
   Recuerda    *\(\Rightarrow\;\)Elige \(\deg R\) que satisface \(2\deg R + 1 = \deg A + \deg R + d\)*

   Dado modelo del proceso \[H(z) = \frac{B(z)}{A(z)} = \frac{b_0z + b_1}{z^2 + a_1z + a_2}\] y \(d=2\)  ¿Cuál es el orden apropiado del controlador 
\[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^n + s_1z^{n-1} + \cdots + s_n}{z^n + r_1 z^{n-1} + \cdots + r_n}\]
para que se puede determinar todos los parametros usando la ecuación diofantina

   \[ A(z)R(z) + B(z)S(z) = A_c(z)A_o(z)?\]

  |         1. | 2. |
  | 3. \(n=3\) | 4. |
  |            |    |


** Determinando el orden del controlador - Ejercicio 3
   Dado modelo del proceso \[H(z) = \frac{B(z)}{A(z)} = \frac{b_0z + b_1}{z^2 + a_1z + a_2}\] y \(d=2\)   el controlador aproprioado es 
\[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^3 + s_1z^2 + s_2z + s_3}{z^3 + r_1 z^2 + r_2z + r_3}.\]
¿Cuáles son los grados permisibles del polinomio observador \(A_o(z)\) en
   \[ A(z)R(z)z^2 + B(z)S(z) = A_c(z)A_o(z)?\]

   | 1. \(< 2\) | 2. \( < 3\)    |
   | 3. \(> 2\) | 4. \( \le 3 \) |

** Determining the order of the controller - Exercise 3, Solución
   With the plant model \[H(z) = \frac{B(z)}{A(z)} = \frac{b_0z + b_1}{z^2 + a_1z + a_2}\] and \(d=2\)    the appropriate degree of the controller is 3
\[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^3 + s_1z^2 + s_2z + s_3}{z^3 + r_1 z^2 + r_2z + r_3}.\]
   What are the possible choices of the degree of the observer polynomial \(A_o(z)\) in
   \[ A(z)R(z)z^2 + B(z)S(z) = A_c(z)A_o(z)?\]
   | 1. |            2. |
   | 3. | 4. \( \le 3\) |
   

