#+OPTIONS: toc:nil
# #+LaTeX_CLASS: koma-article 

#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation,aspectratio=169]
#+OPTIONS: H:2

#+LaTex_HEADER: \usepackage{khpreamble}
#+LaTex_HEADER: \usepackage{amssymb}
#+LaTex_HEADER: \DeclareMathOperator{\shift}{q}
#+LaTex_HEADER: \DeclareMathOperator{\diff}{p}

#+title: Polynomial pole placement
# #+date: 2018-08-29


* Intro

** Goal of today's lecture 					      :slide:
    Understand key concepts of the two-degree-of-freedom controller structure.


* 2-dof controller

** Two-degree-of-freedom controller
#+BEGIN_CENTER 
 \includegraphics[width=0.8\linewidth]{../../figures/2dof-block-explicit}
#+END_CENTER

* Key concepts
** Three key concepts
   1. Where to place the poles of the closed-loop system.
   2. The /sensitivity function/ and the /complementary sensitivity function/.
   3. How to determine the order of the controller.

** The closed-loop poles
   Complex poles in the s-plane
   #+begin_center
   \includegraphics[width=0.45\linewidth]{../../figures/implane-second-order-poles}
   #+end_center

** The closed-loop poles
   Given specifications on the velocity and damping of the closed-loop system
   \[ t_s \approx \frac{4}{\zeta\omega_n} < 1 s \qquad \zeta \approx \frac{-\ln (\%OS/100)}{\sqrt{\pi^2 + \ln^2(\%OS/100)}}, \quad OS < 10\%  \]
   gives
   \[ \zeta > 0.59,  \qquad \zeta\omega_n > 4\]

   #+begin_center
   \includegraphics[width=0.6\linewidth]{../../figures/step-response-specifications}
   #+end_center

** Closed-loop poles
   *Activity* Given the specifications \( \zeta > 0.59\) and \( \zeta\omega_n > 4\), mark the regions in the s-plane and in the z-plane that corresponds to the specifications.
#+BEGIN_CENTER 
*plano s* \hspace*{0.4\linewidth} *plano z*\\
\includegraphics[height=0.61\textheight]{../../figures/sgrid-crop} \hspace*{3mm}
\includegraphics[height=0.6\textheight]{../../figures/zgrid-crop}\\
#+END_CENTER

** Closed-loop poles - Solution
** Closed-loop poles - Solution
   #+begin_center
   \includegraphics[height=0.9\textheight]{../../figures/screenshot-2020-07-14.png}
   #+end_center

** The sensitivity and the complementary sensitivity
** Two-degree-of-freedom controller
#+BEGIN_CENTER 
 \includegraphics[width=0.8\linewidth]{../../figures/2dof-block-explicit}
#+END_CENTER

\begin{align*}
Y(z) &= G_c(z)U_c(z) + \overbrace{S_s(z)}^{\text{sensib}}V(z) - \overbrace{T_s(z)}^{\text{sens compl}}N(z)\\
     &= \frac{F_f(z)H(z)}{1 + F_b(z)z^{-d}H(z)}U_c(z) + \frac{1}{1 + F_b(z)z^{-d}H(z)}V(z)  - \frac{z^{-d}F_b(z)H(z)}{1 + F_b(z)z^{-d}H(z)}N(z)\\
\end{align*}

** Two-degree-of-freedom controller
#+BEGIN_CENTER 
 \includegraphics[width=0.7\linewidth]{../../figures/2dof-block-explicit}
#+END_CENTER

\begin{align*}
Y(z)     &= \frac{F_f(z)H(z)}{1 + z^{-d}F_b(z)H(z)}U_c(z) + \overbrace{\frac{1}{1 + z^{-d}F_b(z)H(z)}}^{S_s(z)}V(z)  - \overbrace{\frac{z^{-d}F_b(z)H(z)}{1 + z^{-d}F_b(z)H(z)}}^{T_s(z)}N(z)\\
\end{align*}
 
*Evidently* \( S_s(z) + T_s(z) = 1\) *Conclusion:* One must find a balance between disturbance rejection and noise attenuation.

** The sensitivity and the complementary sensitivity
*Activity* Mark in the complex plane the points indicated in the Bode plot of the two systems \(S_s(z)\) and \(T_s(z)\). Verify that the vector sum is equal to 1.
#+begin_center
\includegraphics[width=0.7\linewidth]{../matlab/bode-sensitivity-exercise-crop}
#+end_center

** The sensitivity and the complementary sensitivity
    \pgfmathsetmacro{\Smag}{0.12}
    \pgfmathsetmacro{\Sarg}{70}
    \pgfmathsetmacro{\Sreal}{\Smag*cos(\Sarg)}
    \pgfmathsetmacro{\Sim}{\Smag*sin(\Sarg)}
    \pgfmathsetmacro{\Tmag}{0.98}
    \pgfmathsetmacro{\Targ}{-6}
    \pgfmathsetmacro{\Treal}{\Tmag*cos(\Targ)}
    \pgfmathsetmacro{\Tim}{\Tmag*sin(\Targ)}
*Point 1:* \(\omega=0.1\), \(T_s(0.1) = 10^{-0.149/20}\mathrm{e}^{-i6^o} = 0.98\mathrm{e}^{-i6^o} = 0.97 - i0.1\), \(S_s(0.1) = 10^{-18/20}\mathrm{e}^{i70^o} = 0.12\mathrm{e}^{i70^o} = 0.04 + i0.11 \)
#+begin_export latex
\begin{center}
  \begin{tikzpicture}[scale=1.6]

    \draw[->] (-2, 0) -- (2, 0) node[below] {Re};
    \draw[->] (0,-2) -- (0,2) node[left] {Im};
    \node[circle, fill, orange, inner sep= 1pt] (Tone) at (\Treal, \Tim) {};
    \draw[thin, ->, orange] (0,0) to (Tone);
    \node[circle, fill, blue!80, inner sep= 1pt] (Sone) at (\Sreal, \Sim) {};
    \draw[thin, ->, blue!80] (0,0) to (Sone);
    \draw (1,0) -- (1,-0.05) node[below] {1};
    \draw (-1,0) -- (-1,-0.05) node[below] {-1};
    \draw (0,1) -- (-0.05,1) node[left] {i};
    \draw (0,-1) -- (-0.05,-1) node[left] {-i};
  \end{tikzpicture}
\end{center}
#+end_export

** The sensitivity and the complementary sensitivity - Solution

** The sensitivity and the complementary sensitivity - Solution
    \pgfmathsetmacro{\Smag}{0.12}
    \pgfmathsetmacro{\Sarg}{70}
    \pgfmathsetmacro{\Tmag}{0.98}
    \pgfmathsetmacro{\Targ}{-6}
    \pgfmathsetmacro{\Treal}{\Tmag*cos(\Targ)}
    \pgfmathsetmacro{\Tim}{\Tmag*sin(\Targ)}

    \pgfmathsetmacro{\Smagtwo}{0.12}
    \pgfmathsetmacro{\Sargtwo}{70}
    \pgfmathsetmacro{\Srealtwo}{\Smagtwo*cos(\Sargtwo)}
    \pgfmathsetmacro{\Simtwo}{\Smag*sin(\Sarg)}
    \pgfmathsetmacro{\Tmagtwo}{0.98}
    \pgfmathsetmacro{\Targtwo}{-6}

#+begin_export latex
\begin{center}
  \begin{tikzpicture}[scale=1.6]

    \draw[->] (-2, 0) -- (2, 0) node[below] {Re};
    \draw[->] (0,-2) -- (0,2) node[left] {Im};
    \draw (1,0) -- (1,-0.05) node[below] {1};
    \draw (-1,0) -- (-1,-0.05) node[below] {-1};
    \draw (0,1) -- (-0.05,1) node[left] {i};
    \draw (0,-1) -- (-0.05,-1) node[left] {-i};
 

    \foreach \Tmag/\Targ/\nn in {-0.149/-6/1, 3.44/-88/2, -19/-196/3} {
       \pgfmathsetmacro{\Treal}{pow(10,\Tmag/20)*cos(\Targ)}
       \pgfmathsetmacro{\Tim}{pow(10,\Tmag/20)*sin(\Targ)}
       \node[circle, fill, orange, inner sep= 1pt] (Tone) at (\Treal, \Tim) {};
           \draw[thin, ->, orange] (0,0) to (Tone) node[right] {\tiny \nn};
	   }
    \foreach \Smag/\Sarg/\nn in {-18/78/1, 4.9/57/2, 0.85/-1.67/3} {
       \pgfmathsetmacro{\Sreal}{pow(10,\Smag/20)*cos(\Sarg)}
       \pgfmathsetmacro{\Sim}{pow(10,\Smag/20)*sin(\Sarg)}
       \node[circle, fill, blue!80, inner sep= 1pt] (Sone) at (\Sreal, \Sim) {};
           \draw[thin, ->, blue!80] (0,0) to (Sone) node[right] {\tiny \nn};
	   }

    %\node[circle, fill, blue!80, inner sep= 1pt] (Sone) at (\Sreal, \Sim) {};
    %\draw[thin, ->, blue!80] (0,0) to (Sone);
  \end{tikzpicture}
\end{center}
#+end_export


* RST

** Procedure
   Given plant model \(H(z)=\frac{B(z)}{A(z)}\) and specifications on the desired closed-loop poles \(A_{cl}(z)\)
   1. Find polynomials \(R(z)\) and \(S(z)\) with \(n_R \ge n_S\) such that 
      \[ A(z)R(z)z^{d} + B(z)S(z) = A_{cl}(z) \]
   2. Factor the closed-loop polynomials as \(A_{cl}(z) = A_c(z)A_o(z)\), where \(n_{A_o} \le n_R\). Choose
      \[T(z) = t_0 A_o(z),\] where \(t_0 = \frac{A_c(1)}{B(1)}\).

   The control law is then
   \[ R(q) u(k) = T(q)u_c(k) - S(q)y(k). \]
   The closed-loop response to the command signal is given by
   \[ A_c(q)y(k) = t_0 B(q) u_c(k). \]
** Determining the order of the controller
   With Diophantine equation 
      \[ A(z)R(z)z^{d} + B(z)S(z) = A_{cl}(z) \qquad (*) \]
   and feedback controller
   \[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^n + s_1z^{n-1} + \cdots + s_n}{z^n + r_1 z^{n-1} + \cdots + r_n}\]
   *How should we choose the order of the controller?* Note:
   - the controller has $n+n+1 = 2\deg R + 1$ unknown parameters
   - the LHS of \((*)\) has degree $\deg \big(A(z)R(z)z^d + B(z)S(z)\big) = \deg A + \deg R + d$
   - The diophantine gives as many (nontrivial) equations as the degree of the polynomials on each side when we set the coefficients equal.

     *\(\Rightarrow\;\)Choose \(\deg R\) so that \(2\deg R + 1 = \deg A + \deg R + d\)*
     

** Determining the order of the controller - Exercise
   With the plant model \[H(z) = \frac{B(z)}{A(z)} = \frac{b}{z + a}\] and \(d=0\) (no delay), what is the appropriate degree of the controller 
\[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^n + s_1z^{n-1} + \cdots + s_n}{z^n + r_1 z^{n-1} + \cdots + r_n}\]
   so that all parameters can be determined from the diophantine equation
   \[ A(z)R(z) + B(z)S(z) = A_c(z)A_o(z)?\]
   | 1. \(n = 0\) | 2. \(n = 1\) |
   | 3. \(n=2\)   | 4. \(n=3\)   |

** Determining the order of the controller - Exercise - Solution 
   With the plant model \[H(z) = \frac{B(z)}{A(z)} = \frac{b}{z + a}\] and \(d=0\) (no delay), what is the appropriate degree of the controller \[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^n + s_1z^{n-1} + \cdots + s_n}{z^n + r_1 z^{n-1} + \cdots + r_n}\]
   so that all parameters can be determined from the diophantine equation
   \[ A(z)R(z) + B(z)S(z) = A_c(z)A_o(z)?\]
   | 1. \(n = 0\) | 2.           |
   | 3.           | 4.           |

* Skip - on Canvas as quiz instead                                 :noexport:
** Determining the order of the controller - Exercise 2
   With the plant model \[H(z) = \frac{B(z)}{A(z)} = \frac{b_0z + b_1}{z^2 + a_1z + a_2}\] and \(d=2\), what is the appropriate degree of the controller \[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^n + s_1z^{n-1} + \cdots + s_n}{z^n + r_1 z^{n-1} + \cdots + r_n}\]
   so that all parameters can be determined from the diophantine equation
   \[ A(z)R(z)z^2 + B(z)S(z) = A_c(z)A_o(z)?\]
   | 1. \(n = 1\) | 2. \(n = 2\) |
   | 3. \(n=3\)   | 4. \(n=4\)   |

** Determining the order of the controller - Exercise 2
   With the plant model \[H(z) = \frac{B(z)}{A(z)} = \frac{b_0z + b_1}{z^2 + a_1z + a_2}\] and \(d=2\), what is the appropriate degree of the controller \[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^n + s_1z^{n-1} + \cdots + s_n}{z^n + r_1 z^{n-1} + \cdots + r_n}\]
   so that all parameters can be determined from the diophantine equation
   \[ A(z)R(z)z^2 + B(z)S(z) = A_c(z)A_o(z)?\]
   | 1.           | 2.           |
   | 3. \(n=3\)   | 4.           |

** Determining the order of the controller - Exercise 3
   With the plant model \[H(z) = \frac{B(z)}{A(z)} = \frac{b_0z + b_1}{z^2 + a_1z + a_2}\] and \(d=2\)    the appropriate degree of the controller is 3 
\[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^3 + s_1z^2 + s_2z + s_3}{z^3 + r_1 z^2 + r_2z + r_3}.\]
   What are the possible choices of the degree of the observer polynomial \(A_o(z)\) in
   \[ A(z)R(z)z^2 + B(z)S(z) = A_c(z)A_o(z)?\]
   | 1. less than 2   | 2. less than 3             |
   | 3. higher than 2 | 4. less than or equal to 3 |
   
** Determining the order of the controller - Exercise 3
   With the plant model \[H(z) = \frac{B(z)}{A(z)} = \frac{b_0z + b_1}{z^2 + a_1z + a_2}\] and \(d=2\)    the appropriate degree of the controller is 3
\[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^3 + s_1z^2 + s_2z + s_3}{z^3 + r_1 z^2 + r_2z + r_3}.\]
   What are the possible choices of the degree of the observer polynomial \(A_o(z)\) in
   \[ A(z)R(z)z^2 + B(z)S(z) = A_c(z)A_o(z)?\]
   | 1. |                         2. |
   | 3. | 4. less than or equal to 3 |
   
** Where to place the closed-loop poles?
#+BEGIN_CENTER 
\begin{tabular}{cc}
 \includegraphics[width=0.41\linewidth]{../../figures/sgrid-crop}
& \includegraphics[width=0.43\linewidth]{../../figures/zgrid-crop}\\
s-plane & z-plane
\end{tabular}
#+END_CENTER

** Example: RST control of power-plant dam			   :noexport:
#+BEGIN_CENTER 
 \includegraphics[width=0.6\linewidth]{../../figures/kraftverk}
#+END_CENTER

Plant dynamics: \( x(t) = x(t-1) -v(t) + u(t) \)

*** Notes							   :noexport:
    - x is change in level of water in the dam from some operating point Volume = Volume_0 + x
    - u is change in flow through dam gates from some operating point. 
    - v is change in flow out. Either through increase in flow through power dam or decrease in river  
      d/dt Vol =  d/dt (Vol_0 + x(t)) = flow in - flow out
               = n_0 - v_0 - v(t) - u_0 + u(t), with n_0 - v_0 - u_0 = 0   
      dx/dt = u - v. 

    - Model  X = \frac{z}{z-1} (U-V) 

    - H(z) = B(z)/A(z) = z/(z-1). 

    - Diophantine eqn
      AR + BS = Ac
      (z-1)R + zS = Ac
      With first-order controller S/R = (s0z + s1)/(z + r1)
      (z-1)(z+r1) + z(s0z + s1) = (z-0.7)^2 , Ac = Acl = (z-0.7)^2 
      or Ac = Acl Ao = (z-0.7)(z-a) 

      (z-1)(z+r1) + s0z^2 + s1z = (z-0.7)(z-a)
      z^2 - (1-r1)z -r1  + s0z^2 + s1z = z^2 - (0.7+a)z + 0.7*a.
      z^2: 1 + s0 = 1   => s0=0
      z^1: -(1-r1) + s1 = -(0.7+a)
      z^0: -r1 = 0.7a

      
      r1s0s1 = [0, 1, 0; 1, 0, 1; -1, 0, 0]\[1; -0.7-a; 0.7*a] 


      (-2+s0) = -0.7-a => s0 = 1.3-a
      s1 = 0.7*a - 1

      We have Gc = T/R B/A / (1 + S/R B/A) = TB / (AR + BS) = TB / (Ao Ac)
      Let T = Ao*t_0
      Gc = t_0 B / Ac, Want Gc(1) = 1 
      t_0 = Ac(1) / B(1) = (1-0.7)/1 = 0.3.


      Try 
      
