#+OPTIONS: toc:nil
# #+LaTeX_CLASS: koma-article 

#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation,aspectratio=169]
#+OPTIONS: H:2

#+LaTex_HEADER: \usepackage{khpreamble}
#+LaTex_HEADER: \usepackage{amssymb}
#+LaTex_HEADER: \DeclareMathOperator{\shift}{q}
#+LaTex_HEADER: \DeclareMathOperator{\diff}{p}

#+title: Control computarizado - Asignación de polos (RST posicional)
#+date: 2020-07-14

* What do I want the students to understand?			   :noexport:
  - How to design a RST controller

* Which activities will the students do?			   :noexport:
  1. Rank four different pole placements
  2. Determine order of controller in different cases

* Intro

** Objetivo                                                           :slide:
   - Entender diseño de un controlador por asignación de polos

* Tiempo de muestreo
** Tiempo de muestreo
   *Un tiempo de muestreo, \(h\), adecuado depende de la velocidad del proceso a controlar y/o la velocidad deseada del sistema en lazo cerrado*  
*** Reglas de oro (Åström & Wittenmark)
    1. Para sistemas con respuesta al escalón *sin* sobrepaso: *4 a 10* muestreos en un tiempo de subida. \[ \frac{t_r}{h} \approx 4 \; \text{a} \; 10 \]
       #+begin_export latex
	     \begin{center}
	     \def\TT{1}
	     \pgfmathsetmacro{\hh}{\TT/6}
	       \begin{tikzpicture}
		 \begin{axis}[
		   width=14cm,
		   height=4cm,
		   xlabel={$t$},
		   ylabel={$y(kh)$},
		   xmin={-2.5*\hh},
		   xmax={20*\hh},
		   ytick=\empty,
		   ]
         
		   \addplot+[black, ycomb, domain=-2:20, samples=23,variable=k] ( {k*\hh}, {(k*\hh>=0)*(1 - exp(-k*\hh/\TT) }); 
         
		 \end{axis}
	       \end{tikzpicture}
	     \end{center}

  
       #+end_export


** Tiempo de muestreo
*** Reglas de oro (Åström & Wittenmark)
    2. [@2] Para sistemas con respuesta tipo segunda orden subamortiguada \( G(s) = \frac{\omega_n^2}{s^2 + 2\zeta\omega_n s + \omega_n^2}:\) 
       \[ \omega_n h \approx 0.2 \; \text{to} \; 0.6 \qquad \text{Ejemplo con}\; h = \frac{0.4}{\omega_n}:\]

       #+begin_export latex
       \begin{center}
       \includegraphics[width=12cm]{second-order-response-example}
       \end{center}
       #+end_export
** Tiempo de muestreo
*** Reglas de oro (Åström & Wittenmark)
    3. [@3] Si conocemos la frecuencia de cross-over, \(\omega_c\), deseada, podemos eligir un tiempo de muestreo basado en un análisis del cambio de fase negativo causado por el muestreo y retención. La regla dice que este cambio negativo sea entre -5 y -15 grados. El efecto de muestreo y retención es approximadamente un retraso de \(h/2\), \(\mathrm{e}^{-sh/2}\). Resulta la regla
       \[ \arg \mathrm{e}^{-i\omega_c h/2} = -\omega_c h/2 \approx -\frac{5\pi}{180} \; \text{a} \; -\frac{15\pi}{180}\]

* Asignación de polos - Repetición
** Diseño por asignación de polos
** Asignación de polos - Un ejemplo
   #+begin_export latex
  \begin{center}
  \begin{tikzpicture}
  \tikzset{node distance=2cm, 
      block/.style={rectangle, draw, minimum height=12mm, minimum width=14mm},
      sumnode/.style={circle, draw, inner sep=2pt}        
  }

    \node[coordinate] (input) {};
    \node[sumnode, right of=input, node distance=20mm] (sum) {\tiny $\sum$};
    \node[block, right of=sum, node distance=32mm] (PI) {$F_{PI}(z) = K_c\frac{z -1 + \frac{h}{T_i}}{z-1}$};
    \node[block,right of=PI, node distance=40mm] (plant) {$H(z) = \frac{b}{z-a}$};
    \node[coordinate, right of=plant, node distance=30mm] (output) {};
    \node[coordinate, right of=plant, node distance=22mm] (measure) {};
    \draw[->] (input) -- node[above, pos=0.2] {$r(k)$} (sum);
    \draw[->] (sum) -- node[above, ] {$e(k)$} (PI);
    \draw[->] (PI) -- node[above] {$u(k)$} (plant);
    \draw[->] (plant) -- node[at end, above] {$y(k)$} (output);
    \draw[->] (measure) -- ++(0,-16mm) -| (sum) node[left, pos=0.96] {$-$};
  \end{tikzpicture}
  \end{center}
  #+end_export

  *Queremos un sistema de lazo cerrado criticalmente amortiguado con dos polos en \(z = \alpha, \quad 0 < \alpha < 1 \)*


** Asignación de polos	   
   #+begin_export latex
  \begin{center}
  \begin{tikzpicture}
  \tikzset{node distance=2cm, 
      block/.style={rectangle, draw, minimum height=12mm, minimum width=14mm},
      sumnode/.style={circle, draw, inner sep=2pt}        
  }

    \node[coordinate] (input) {};
    \node[sumnode, right of=input, node distance=20mm] (sum) {\tiny $\sum$};
    \node[block, right of=sum, node distance=32mm] (PI) {$F_{PI}(z) = K_c\frac{z -1 + \frac{h}{T_i}}{z-1}$};
    \node[block,right of=PI, node distance=40mm] (plant) {$H(z) = \frac{b}{z-a}$};
    \node[coordinate, right of=plant, node distance=30mm] (output) {};
    \node[coordinate, right of=plant, node distance=22mm] (measure) {};
    \draw[->] (input) -- node[above, pos=0.2] {$r(k)$} (sum);
    \draw[->] (sum) -- node[above, ] {$e(k)$} (PI);
    \draw[->] (PI) -- node[above] {$u(k)$} (plant);
    \draw[->] (plant) -- node[at end, above] {$y(k)$} (output);
    \draw[->] (measure) -- ++(0,-16mm) -| (sum) node[left, pos=0.96] {$-$};
  \end{tikzpicture}
  \end{center}
  #+end_export

  *Ecuación característica*
  \begin{align*}
  1 + H(z)F_{PI}(z) &= 0\\
  (z-1)(z-a) + K_c b (z - 1 + h/T_i) &= 0
  \end{align*}
  *Polinomio característico*
  \[ \underbrace{(z-1)(z-a) + K_c b (z - 1 + h/T_i)}_{\text{parametrizado}} = \underbrace{(z-\alpha)^2}_{\text{deseado}}\]

  *¿Cómo podemos determinar los parametros del controlador, \(K_c\) y \(T_i\)?* 

** Asignación de polos - Solución
   #+begin_export latex
  \begin{center}
  \begin{tikzpicture}
  \tikzset{node distance=2cm, 
      block/.style={rectangle, draw, minimum height=12mm, minimum width=14mm},
      sumnode/.style={circle, draw, inner sep=2pt}        
  }

    \node[coordinate] (input) {};
    \node[sumnode, right of=input, node distance=20mm] (sum) {\tiny $\sum$};
    \node[block, right of=sum, node distance=32mm] (PI) {$F_{PI}(z) = K_c\frac{z -1 + \frac{h}{T_i}}{z-1}$};
    \node[block,right of=PI, node distance=40mm] (plant) {$H(z) = \frac{b}{z-a}$};
    \node[coordinate, right of=plant, node distance=30mm] (output) {};
    \node[coordinate, right of=plant, node distance=22mm] (measure) {};
    \draw[->] (input) -- node[above, pos=0.2] {$r(k)$} (sum);
    \draw[->] (sum) -- node[above, ] {$e(k)$} (PI);
    \draw[->] (PI) -- node[above] {$u(k)$} (plant);
    \draw[->] (plant) -- node[at end, above] {$y(k)$} (output);
    \draw[->] (measure) -- ++(0,-16mm) -| (sum) node[left, pos=0.96] {$-$};
  \end{tikzpicture}
  \end{center}
  #+end_export
  Polinomio característico
  \[ \underbrace{z^2 - (1+a -K_cb)z + K_cb(h/T_i - 1) + a}_{\text{parametrizado}} = \underbrace{z^2 -2\alpha z + \alpha^2}_{\text{deseado}}\]

  *Los dos polinomios caracteristicos son iguales solamente si cada uno de los coefficientes correspondientes son iguales. Eso nos da dos ecuaciones en los variables desconocidos:*
  \begin{align*}
  1 + a - K_c b &= 2\alpha \quad \Rightarrow \quad K_c = \frac{1+a-2\alpha}{b}\\
  K_cb(h/T_i - 1) + a &= \alpha^2 \quad \Rightarrow \quad \frac{1}{T_i} = \frac{1}{h}\left(1 + \frac{\alpha^2-a}{K_c b}\right) = \frac{1}{h} \left( \frac{(\alpha-1)^2}{1 + a - 2\alpha}\right) 
  \end{align*}
  

** Asignación de polos	   
   
   *Ligas*

   [[https://mybinder.org/v2/gh/kjartan-at-tec/mr2007-computerized-control/master?filepath=.%2Fapproximating-cont-controller%2Fnotebooks%2FPole-placement-PI-controller-example.ipynb][Solución en mybinder]]

   [[https://github.com/kjartan-at-tec/mr2007-computerized-control/blob/master/approximating-cont-controller/notebooks/Pole-placement-PI-controller-example.ipynb][Solución en github]]
   


* Conceptos claves
** Tres conceptos claves
   1. Dónde poner los polos del sistem en lazo cerrado
   2. La función de /sensibilidad/ y la función de /sensibilidad complementaria/
   3. Determinar el orden del controlador

** Los polos del sistema en lazo cerrado
   Polos complejos en el plano $s$:
   #+begin_center
   \includegraphics[width=0.45\linewidth]{../../figures/implane-second-order-poles}
   #+end_center

** Los polos del sistema en lazo cerrado
   Dado especificaciónes de la velocidad y amortiguación del sistema en lazo cerrado
   \[ t_s \approx \frac{4}{\zeta\omega_n} < 1 s \qquad \zeta \approx \frac{-\ln (\%OS/100)}{\sqrt{\pi^2 + \ln^2(\%OS/100)}}, \quad OS < 10\%  \]
   resulta en 
   \[ \zeta > 0.59,  \qquad \zeta\omega_n > 4\]

   #+begin_center
   \includegraphics[width=0.6\linewidth]{../../figures/step-response-specifications}
   #+end_center

** Los polos del sistema en lazo cerrado
   *Actividad* Dado especificaciones \( \zeta > 0.59\) y \( \zeta\omega_n > 4\), marca las regiones en el plano $s$ y en el plano $z$ que corresponden a las especificaciones.
#+BEGIN_CENTER 
*plano s* \hspace*{0.4\linewidth} *plano z*\\
\includegraphics[height=0.61\textheight]{../../figures/sgrid-crop} \hspace*{3mm}
\includegraphics[height=0.6\textheight]{../../figures/zgrid-crop}\\
#+END_CENTER

** 
   #+begin_center
   \includegraphics[height=0.9\textheight]{../../figures/screenshot-2020-07-14.png}
   #+end_center

** Las funciones de sensibilidad y sensibilidad complementaria
** Controlador de dos grados de libertad
#+BEGIN_CENTER 
 \includegraphics[width=0.8\linewidth]{../../figures/2dof-block-explicit}
#+END_CENTER

\begin{align*}
Y(z) &= G_c(z)U_c(z) + \overbrace{S_s(z)}^{\text{sensib}}V(z) - \overbrace{T_s(z)}^{\text{sens compl}}N(z)\\
     &= \frac{F_f(z)H(z)}{1 + F_b(z)z^{-d}H(z)}U_c(z) + \frac{1}{1 + F_b(z)z^{-d}H(z)}V(z)  - \frac{z^{-d}F_b(z)H(z)}{1 + F_b(z)z^{-d}H(z)}N(z)\\
\end{align*}

** Controlador de dos grados de libertad
#+BEGIN_CENTER 
 \includegraphics[width=0.7\linewidth]{../../figures/2dof-block-explicit}
#+END_CENTER

\begin{align*}
Y(z)     &= \frac{F_f(z)H(z)}{1 + z^{-d}F_b(z)H(z)}U_c(z) + \overbrace{\frac{1}{1 + z^{-d}F_b(z)H(z)}}^{S_s(z)}V(z)  - \overbrace{\frac{z^{-d}F_b(z)H(z)}{1 + z^{-d}F_b(z)H(z)}}^{T_s(z)}N(z)\\
\end{align*}
 
*Evidentemente* \( S_s(z) + T_s(z) = 1\) *Conclusion:* Hay que encontrar un equilibrio entre rechazo a perturbaciones y rechazo a ruido de medida.

** Sensibilidad y sensibilidad complementaria
*Actividad* Marca en el plano complejo los puntos indicados en el diagrama de Bode para ambos sistemas \(S_s(z)\) y \(T_s(z)\). Verifica que la suma vectorial de los puntos es 1.
#+begin_center
\includegraphics[width=0.7\linewidth]{../matlab/bode-sensitivity-exercise-crop}
#+end_center

** Sensibilidad y sensibilidad complementaria
    \pgfmathsetmacro{\Smag}{0.12}
    \pgfmathsetmacro{\Sarg}{70}
    \pgfmathsetmacro{\Sreal}{\Smag*cos(\Sarg)}
    \pgfmathsetmacro{\Sim}{\Smag*sin(\Sarg)}
    \pgfmathsetmacro{\Tmag}{0.98}
    \pgfmathsetmacro{\Targ}{-6}
    \pgfmathsetmacro{\Treal}{\Tmag*cos(\Targ)}
    \pgfmathsetmacro{\Tim}{\Tmag*sin(\Targ)}
*Punto 1:* \(\omega=0.1\), \(T_s(0.1) = 10^{-0.149/20}\mathrm{e}^{-i6^o} = 0.98\mathrm{e}^{-i6^o} = 0.97 - i0.1\), \(S_s(0.1) = 10^{-18/20}\mathrm{e}^{i70^o} = 0.12\mathrm{e}^{i70^o} = 0.04 + i0.11 \)
#+begin_export latex
\begin{center}
  \begin{tikzpicture}[scale=1.6]

    \draw[->] (-2, 0) -- (2, 0) node[below] {Re};
    \draw[->] (0,-2) -- (0,2) node[left] {Im};
    \node[circle, fill, orange, inner sep= 1pt] (Tone) at (\Treal, \Tim) {};
    \draw[thin, ->, orange] (0,0) to (Tone);
    \node[circle, fill, blue!80, inner sep= 1pt] (Sone) at (\Sreal, \Sim) {};
    \draw[thin, ->, blue!80] (0,0) to (Sone);
    \draw (1,0) -- (1,-0.05) node[below] {1};
    \draw (-1,0) -- (-1,-0.05) node[below] {-1};
    \draw (0,1) -- (-0.05,1) node[left] {i};
    \draw (0,-1) -- (-0.05,-1) node[left] {-i};
  \end{tikzpicture}
\end{center}
#+end_export

** Sensibilidad y sensibilidad complementaria -  Solución
** Sensibilidad y sensibilidad complementaria -  Solución
    \pgfmathsetmacro{\Smag}{0.12}
    \pgfmathsetmacro{\Sarg}{70}
    \pgfmathsetmacro{\Tmag}{0.98}
    \pgfmathsetmacro{\Targ}{-6}
    \pgfmathsetmacro{\Treal}{\Tmag*cos(\Targ)}
    \pgfmathsetmacro{\Tim}{\Tmag*sin(\Targ)}

    \pgfmathsetmacro{\Smagtwo}{0.12}
    \pgfmathsetmacro{\Sargtwo}{70}
    \pgfmathsetmacro{\Srealtwo}{\Smagtwo*cos(\Sargtwo)}
    \pgfmathsetmacro{\Simtwo}{\Smag*sin(\Sarg)}
    \pgfmathsetmacro{\Tmagtwo}{0.98}
    \pgfmathsetmacro{\Targtwo}{-6}

#+begin_export latex
\begin{center}
  \begin{tikzpicture}[scale=1.6]

    \draw[->] (-2, 0) -- (2, 0) node[below] {Re};
    \draw[->] (0,-2) -- (0,2) node[left] {Im};
    \draw (1,0) -- (1,-0.05) node[below] {1};
    \draw (-1,0) -- (-1,-0.05) node[below] {-1};
    \draw (0,1) -- (-0.05,1) node[left] {i};
    \draw (0,-1) -- (-0.05,-1) node[left] {-i};
 

    \foreach \Tmag/\Targ/\nn in {-0.149/-6/1, 3.44/-88/2, -19/-196/3} {
       \pgfmathsetmacro{\Treal}{pow(10,\Tmag/20)*cos(\Targ)}
       \pgfmathsetmacro{\Tim}{pow(10,\Tmag/20)*sin(\Targ)}
       \node[circle, fill, orange, inner sep= 1pt] (Tone) at (\Treal, \Tim) {};
           \draw[thin, ->, orange] (0,0) to (Tone) node[right] {\tiny \nn};
	   }
    \foreach \Smag/\Sarg/\nn in {-18/78/1, 4.9/57/2, 0.85/-1.67/3} {
       \pgfmathsetmacro{\Sreal}{pow(10,\Smag/20)*cos(\Sarg)}
       \pgfmathsetmacro{\Sim}{pow(10,\Smag/20)*sin(\Sarg)}
       \node[circle, fill, blue!80, inner sep= 1pt] (Sone) at (\Sreal, \Sim) {};
           \draw[thin, ->, blue!80] (0,0) to (Sone) node[right] {\tiny \nn};
	   }

    %\node[circle, fill, blue!80, inner sep= 1pt] (Sone) at (\Sreal, \Sim) {};
    %\draw[thin, ->, blue!80] (0,0) to (Sone);
  \end{tikzpicture}
\end{center}
#+end_export

* Cancelación de polos del observador
** Controlador de dos grados de libertad
#+BEGIN_CENTER 
 \includegraphics[width=0.7\linewidth]{../../figures/2dof-block-explicit}
#+END_CENTER

\begin{align*}
Y(z) &= \frac{T(z)B(z)z^d}{z^dA(z)R(z) + B(z)S(z)}U_c(z) + \frac{A(z)R(z)z^d}{z^dA(z)R(z) + B(z)S(z)}V(z)\\ & \qquad\qquad\qquad - \frac{S(z)B(z)}{z^dA(z)R(z) + B(z)S(z)}N(z)
\end{align*}
 



** Controlador de dos grados de libertad
\begin{align*}
Y(z) &= \frac{T(z)B(z)z^d}{z^dA(z)R(z) + B(z)S(z)}U_c(z) + \frac{A(z)R(z)z^d}{z^dA(z)R(z) + B(z)S(z)}V(z)\\ & \qquad\qquad\qquad - \frac{S(z)B(z)}{z^dA(z)R(z) + B(z)S(z)}N(z)\\
     &= \frac{T(z)B(z)z^d}{A_c(z)A_o(z)}U_c(z) + \frac{A(z)R(z)z^d}{A_c(z)A_o(z)}V(z)- \frac{S(z)B(z)}{A_c(z)A_o(z)}N(z), \quad \text{elige}\, T(z) = t_0A_o(z)\\
     &= \frac{t_0B(z)z^d}{A_c(z)}U_c(z) + \frac{A(z)R(z)z^d}{A_c(z)A_o(z)}V(z)- \frac{S(z)B(z)}{A_c(z)A_o(z)}N(z)
\end{align*}

** Controlador de dos grados de libertad
#+BEGIN_CENTER 
 \includegraphics[width=0.7\linewidth]{../../figures/2dof-block-explicit}
#+END_CENTER
\begin{align*}
Y(z) &= \frac{t_0B(z)z^d}{A_c(z)}U_c(z) + \frac{A(z)R(z)z^d}{A_c(z)A_o(z)}V(z)- \frac{S(z)B(z)}{A_c(z)A_o(z)}N(z)
\end{align*}

** Controlador de dos grados de libertad
#+BEGIN_CENTER 
 \includegraphics[width=0.7\linewidth]{../../figures/2dof-block-explicit}
#+END_CENTER
\begin{align*}
Y(z) &= \frac{t_0B(z)z^d}{A_c(z)}U_c(z) + \frac{A(z)R(z)z^d}{A_c(z)A_o(z)}V(z)- \frac{S(z)B(z)}{A_c(z)A_o(z)}N(z)
\end{align*}
 *Conclusiones* 1) Hay una separación parcial entre seguimiento de la referencia y rechazo a perturbaciones. 2) Se puede usar los polos correspondientes a las raíces de \(A_o(z)\) para afinar el rechazo a perturbaciones contra rechazo a ruido de medida. 

   
