#+OPTIONS: toc:nil
# #+LaTeX_CLASS: koma-article 

#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation,aspectratio=169]
#+OPTIONS: H:2

#+LaTex_HEADER: \usepackage{khpreamble}
#+LaTex_HEADER: \usepackage{amssymb}
#+LaTex_HEADER: \DeclareMathOperator{\shift}{q}
#+LaTex_HEADER: \DeclareMathOperator{\diff}{p}

#+title: Control computarizado - Asignaciónde polos (RST posicional)
# #+date: 2018-08-29

* What do I want the students to understand?			   :noexport:
  - How to design a RST controller

* Which activities will the students do?			   :noexport:
  1. Rank four different pole placements
  2. Determine order of controller in different cases

* Intro

** Objetivo                                                           :slide:
   - Entender diseño de un controlador por asignación de polos

* 2-dof controller

** Controlador de dos grados de libertad
#+BEGIN_CENTER 
 \includegraphics[width=0.8\linewidth]{../../figures/2dof-block-explicit}
#+END_CENTER
   
* RST

** Procedimiento
   Dado modelo del proceso \(H(z)=\frac{B(z)}{A(z)}\), y specificaciones de polos deseados del sistema en lazo cerrado \(A_{cl}(z) = (z-\alpha_1)(z-\alpha_2) \cdots (z-\alpha_{n_c})\)
   1. Determina la ecuación diofántica
      \[ A(z)R(z)z^{d} + B(z)S(z) = A_{cl}(z) \]
   1. Determina polinomios \(R(z)\) y \(S(z)\) donde \(n_R \ge n_S\) que satisfican
      \[ A(z)R(z)z^{d} + B(z)S(z) = A_{cl}(z) \]
   2. Factoriza el polinomio caracteristico del lazo cerrado \(A_{cl}(z) = A_c(z)A_o(z)\), donde \(n_{A_o} \le n_R\). Eliga
      \[T(z) = t_0 A_o(z),\] donde \(t_0 = \frac{A_c(1)}{B(1)}\).

   Nos da el ley de control 
   \[ R(q) u(k) = T(q)u_c(k) - S(q)y(k). \]
   y la respuesta en lazo cerrado a la señal de referencia
   \[ A_c(q)y(k) = t_0 B(q) u_c(k). \]
** Determinación del orden del controlador
   Tenemos la ecuación diafóntica
      \[ A(z)R(z)z^{d} + B(z)S(z) = A_{cl}(z) \qquad (*) \]
   y el controlador de retroalimentación
   \[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^n + s_1z^{n-1} + \cdots + s_n}{z^n + r_1 z^{n-1} + \cdots + r_n}\]
   *¿Cómo decidir el orden del controlador?* Nota
   - el controlador tiene $n+n+1 = 2\deg R + 1$ parámetros desconocidos
   - el lado izquierdo de \((*)\) tiene el grado $\deg \big(A(z)R(z)z^d + B(z)S(z)\big) = \deg A + \deg R + d$
   - la ecuación diofántica nos un numero de ecuaciones (no-triviales) igual a su grado, al poner coeficientes de los dos lados iguales.

     *\(\Rightarrow\;\)Choose \(\deg R\) so that \(2\deg R + 1 = \deg A + \deg R + d\)*
     

** Determining the order of the controller - Exercise 1
   With the plant model \[H(z) = \frac{B(z)}{A(z)} = \frac{b}{z + a}\] and \(d=0\) (no delay), what is the appropriate degree of the controller 
\[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^n + s_1z^{n-1} + \cdots + s_n}{z^n + r_1 z^{n-1} + \cdots + r_n}\]
   so that all parameters can be determined from the diophantine equation
   \[ A(z)R(z) + B(z)S(z) = A_c(z)A_o(z)?\]
   | 1. \(n = 0\) | 2. \(n = 1\) |
   | 3. \(n=2\)   | 4. \(n=3\)   |

** Determining the order of the controller - Exercise 1
   With the plant model \[H(z) = \frac{B(z)}{A(z)} = \frac{b}{z + a}\] and \(d=0\) (no delay), what is the appropriate degree of the controller \[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^n + s_1z^{n-1} + \cdots + s_n}{z^n + r_1 z^{n-1} + \cdots + r_n}\]
   so that all parameters can be determined from the diophantine equation
   \[ A(z)R(z) + B(z)S(z) = A_c(z)A_o(z)?\]
   | 1. \(n = 0\) | 2.           |
   | 3.           | 4.           |

** Determining the order of the controller - Exercise 2
   With the plant model \[H(z) = \frac{B(z)}{A(z)} = \frac{b_0z + b_1}{z^2 + a_1z + a_2}\] and \(d=2\), what is the appropriate degree of the controller \[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^n + s_1z^{n-1} + \cdots + s_n}{z^n + r_1 z^{n-1} + \cdots + r_n}\]
   so that all parameters can be determined from the diophantine equation
   \[ A(z)R(z)z^2 + B(z)S(z) = A_c(z)A_o(z)?\]
   | 1. \(n = 1\) | 2. \(n = 2\) |
   | 3. \(n=3\)   | 4. \(n=4\)   |

** Determining the order of the controller - Exercise 2
   With the plant model \[H(z) = \frac{B(z)}{A(z)} = \frac{b_0z + b_1}{z^2 + a_1z + a_2}\] and \(d=2\), what is the appropriate degree of the controller \[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^n + s_1z^{n-1} + \cdots + s_n}{z^n + r_1 z^{n-1} + \cdots + r_n}\]
   so that all parameters can be determined from the diophantine equation
   \[ A(z)R(z)z^2 + B(z)S(z) = A_c(z)A_o(z)?\]
   | 1.           | 2.           |
   | 3. \(n=3\)   | 4.           |

** Determining the order of the controller - Exercise 3
   With the plant model \[H(z) = \frac{B(z)}{A(z)} = \frac{b_0z + b_1}{z^2 + a_1z + a_2}\] and \(d=2\)    the appropriate degree of the controller is 3 
\[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^3 + s_1z^2 + s_2z + s_3}{z^3 + r_1 z^2 + r_2z + r_3}.\]
   What are the possible choices of the degree of the observer polynomial \(A_o(z)\) in
   \[ A(z)R(z)z^2 + B(z)S(z) = A_c(z)A_o(z)?\]
   | 1. less than 2   | 2. less than 3             |
   | 3. higher than 2 | 4. less than or equal to 3 |
   
** Determining the order of the controller - Exercise 3
   With the plant model \[H(z) = \frac{B(z)}{A(z)} = \frac{b_0z + b_1}{z^2 + a_1z + a_2}\] and \(d=2\)    the appropriate degree of the controller is 3
\[F_b(z) = \frac{S(z)}{R(z)} = \frac{s_0z^3 + s_1z^2 + s_2z + s_3}{z^3 + r_1 z^2 + r_2z + r_3}.\]
   What are the possible choices of the degree of the observer polynomial \(A_o(z)\) in
   \[ A(z)R(z)z^2 + B(z)S(z) = A_c(z)A_o(z)?\]
   | 1. |                         2. |
   | 3. | 4. less than or equal to 3 |
   
** Where to place the closed-loop poles?
#+BEGIN_CENTER 
\begin{tabular}{cc}
 \includegraphics[width=0.41\linewidth]{../../figures/sgrid-crop}
& \includegraphics[width=0.43\linewidth]{../../figures/zgrid-crop}\\
s-plane & z-plane
\end{tabular}
#+END_CENTER

** Example: RST control of power-plant dam			   :noexport:
#+BEGIN_CENTER 
 \includegraphics[width=0.6\linewidth]{../../figures/kraftverk}
#+END_CENTER

Plant dynamics: \( x(t) = x(t-1) -v(t) + u(t) \)

*** Notes							   :noexport:
    - x is change in level of water in the dam from some operating point Volume = Volume_0 + x
    - u is change in flow through dam gates from some operating point. 
    - v is change in flow out. Either through increase in flow through power dam or decrease in river  
      d/dt Vol =  d/dt (Vol_0 + x(t)) = flow in - flow out
               = n_0 - v_0 - v(t) - u_0 + u(t), with n_0 - v_0 - u_0 = 0   
      dx/dt = u - v. 

    - Model  X = \frac{z}{z-1} (U-V) 

    - H(z) = B(z)/A(z) = z/(z-1). 

    - Diophantine eqn
      AR + BS = Ac
      (z-1)R + zS = Ac
      With first-order controller S/R = (s0z + s1)/(z + r1)
      (z-1)(z+r1) + z(s0z + s1) = (z-0.7)^2 , Ac = Acl = (z-0.7)^2 
      or Ac = Acl Ao = (z-0.7)(z-a) 

      (z-1)(z+r1) + s0z^2 + s1z = (z-0.7)(z-a)
      z^2 - (1-r1)z -r1  + s0z^2 + s1z = z^2 - (0.7+a)z + 0.7*a.
      z^2: 1 + s0 = 1   => s0=0
      z^1: -(1-r1) + s1 = -(0.7+a)
      z^0: -r1 = 0.7a

      
      r1s0s1 = [0, 1, 0; 1, 0, 1; -1, 0, 0]\[1; -0.7-a; 0.7*a] 


      (-2+s0) = -0.7-a => s0 = 1.3-a
      s1 = 0.7*a - 1

      We have Gc = T/R B/A / (1 + S/R B/A) = TB / (AR + BS) = TB / (Ao Ac)
      Let T = Ao*t_0
      Gc = t_0 B / Ac, Want Gc(1) = 1 
      t_0 = Ac(1) / B(1) = (1-0.7)/1 = 0.3.


      Try 
      
