#+OPTIONS: toc:nil
# #+LaTeX_CLASS: koma-article 

#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation,aspectratio=1610]
#+OPTIONS: H:2
# #+BEAMER_THEME: Madrid
#+COLUMNS: %45ITEM %10BEAMER_ENV(Env) %10BEAMER_ACT(Act) %4BEAMER_COL(Col) %8BEAMER_OPT(Opt)
     
#+LaTex_HEADER: \usepackage{khpreamble, euscript}
#+LaTex_HEADER: \DeclareMathOperator{\atantwo}{atan2}
#+LaTex_HEADER: \newcommand*{\ctrb}{\EuScript{C}}
#+LaTex_HEADER: \newcommand*{\obsv}{\EuScript{O}}

#+title: Control computarizado - Modelos en espacio de estados

* What do I want the students to understand?			   :noexport:
  - Understand state feedback design

* Which activities will the students do?			   :noexport:
  1. Calculate characteristic equation feedback for double integrator
  2. Write pseudo code to compute control signal


* PMSM - Motor syncrono de Iman permanente

** PMSM - Motor síncrono de imán permanente
   #+begin_center
   \includegraphics[width=0.9\linewidth]{../../figures/permanent-motor.jpg}
   #+end_center
** PMSM - Motor síncrono de imán permanente
   #+begin_center
   \includegraphics[width=0.9\linewidth]{../../figures/pmsm_control_block_diag.png}
   #+end_center

** Modelo identificado
   #+begin_export latex
   \begin{center}
     \begin{tikzpicture}[node distance=32mm, block/.style={rectangle, draw, minimum width=15mm}, sumnode/.style={circle, draw, inner sep=2pt}]
    
       \node[coordinate] (input) {};
       \node[block, right of=input] (plant)  {$H(z) = \frac{b_0z + b_1}{z^2 + a_1 z + a_2}$};
       \node[coordinate, right of=plant] (output) {};

       \draw[->] (input) -- node[above, pos=0.3] {$u(k)$} (plant);
       \draw[->] (plant) -- node[above, near end] {$y(k)$} (output);

       \begin{scope}[yshift=-2cm, xshift = 3cm]
       \node {$\Updownarrow$};
       \end{scope}

       \begin{scope}[yshift=-4cm, node distance=50mm, xshift=-2cm]
       \node[coordinate] (input) {};
       \node[block, right of=input, align=center] (plant)  {$x(k+1) = \Phi x(k) + \Gamma u(k)$\\$y(k) = C x(k)$};
       \node[coordinate, right of=plant] (output) {};

       \draw[->] (input) -- node[above, pos=0.3] {$u(k)$} (plant);
       \draw[->] (plant) -- node[above, near end] {$y(k)$} (output);
       \end{scope}



     \end{tikzpicture}
   \end{center}

   #+end_export

** Formas canónicas
   Dado función de transferencia 
   \[ H(z) = \frac{b_1 z^2 + b_2 z + b_3}{z^3 + a_1z^2 + a_2z + a_3}.\] 
   Encuentra una representación en espacio de estados.
   \begin{align*}
    x(k+1) &= \Phi x(k) + \Gamma u(k) \\
    y(k) &= C x(k)
    \end{align*}

   - Forma canónica de control
   - Forma canónica de observador

** Forma canónica de control
   Dado función de transferencia 
   \[ H(z) = \frac{b_1 z^2 + b_2 z + b_3}{z^3 + a_1z^2 + a_2z + a_3}.\] 

   \begin{align*}
    x(k+1) &= \begin{bmatrix} -a_1 & -a_2 & -a_3\\1 & 0 & 0\\0 & 1 & 0\end{bmatrix} x(k) + \begin{bmatrix}1\\0\\0\end{bmatrix} u(k) \\
    y(k) &= \begin{bmatrix} b_1 & b_2 & b_3 \end{bmatrix} x(k)
    \end{align*}


** Forma canónica de observador
   Dado función de transferencia 
   \[ H(z) = \frac{b_1 z^2 + b_2 z + b_3}{z^3 + a_1z^2 + a_2z + a_3}.\] 

   \begin{align*}
    x(k+1) &= \begin{bmatrix} -a_1 & 1 & 0\\-a_2 & 0 & 1\\-a_3 & 0 & 0\end{bmatrix} x(k) + \begin{bmatrix}b_1\\b_2\\b_3\end{bmatrix} u(k) \\
    y(k) &= \begin{bmatrix} 1 & 0 & 0 \end{bmatrix} x(k)
    \end{align*}


** Formas canónicas - ejercicio
   *Actividad* Encuentra las formas canónicas de control y de observador para la función de transferencia del motor
   \[H(z) = \frac{23.3z - 6.9}{z^2 - 1.40z + 0.61}\]



* Apollo moon lander
** Modelación 
** Ejemplo - El módulo lunar de Apollo

   #+begin_export latex
   \begin{center}
   \includegraphics[width=\linewidth]{fig-apollo}
   \end{center}
   #+end_export
** Ejemplo - El módulo lunar de Apollo

   #+begin_export latex
   \begin{center}
   \includegraphics[width=0.8\linewidth]{fig-apollo}
   \end{center}
   #+end_export
   *Actividad* ¿Cuál es la función de transferencia del sistema?
   \[1: \; G(s) = \frac{k_1 k_2}{s^2}\qquad 2: \; G(s) = \frac{k_1 k_2}{s(s^2 + 1)} \qquad 3: \; G(s) = \frac{k_1 k_2}{s^3}\]

** Ejemplo - El módulo lunar de Apollo

   #+begin_export latex
   \begin{center}
   \includegraphics[width=0.8\linewidth]{fig-apollo}
   \end{center}
   #+end_export
   *Actividad* ¿Que sensores relevantes se puede usar para el control?

** Ejemplo - El módulo lunar de Apollo

   #+begin_export latex
   \begin{center}
   \includegraphics[width=0.7\linewidth]{fig-apollo}
   \end{center}
   #+end_export

   Variables del estado: \( x = \begin{bmatrix} x_1 & x_2 & x_3 \end{bmatrix}^T = \begin{bmatrix} \dot{\theta} & \theta & \dot{z} \end{bmatrix}^T\). Con dinamica
   \[ \begin{cases} \dot{x}_1 =  \ddot{\theta} = k_1 u\\ \dot{x}_2 = \dot{\theta} = x_1\\ \dot{x}_3 = \ddot{z} = k_2\theta = k_2x_2 \end{cases} \]

** Ejemplo - El módulo lunar de Apollo

   Variables del estado: \( x = \begin{bmatrix} x_1 & x_2 & x_3 \end{bmatrix}^T = \begin{bmatrix} \dot{\theta} & \theta & \dot{z} \end{bmatrix}^T\). Con dinamica
   \[ \begin{cases} \dot{x}_1 =  \ddot{\theta} = k_1 u\\ \dot{x}_2 = \dot{\theta} = x_1\\ \dot{x}_3 = \ddot{z} = k_2\theta = k_2x_2 \end{cases} \]

   *Actividad* Llena los matrices y vectores en el modelo de espacio de estados

   \[ \dot{x} = \begin{bmatrix} \dot{x}_1\\\dot{x}_2\\\dot{x}_3\end{bmatrix} = \underbrace{\begin{bmatrix} \quad & \quad &\quad \\\quad & \quad& \quad\\ \quad& \quad &\quad \end{bmatrix}}_{A} \begin{bmatrix} x_1\\x_2\\x_3\end{bmatrix} + \underbrace{\begin{bmatrix} \quad \\ \quad \\\quad  \end{bmatrix}}_{B} u \]


** Modelación - ejercicio

*** Graphics
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
    \includegraphics[height=0.5\textheight]{../../figures/mass-spring-damper}

*** Text
    :PROPERTIES:
    :BEAMER_col: 0.5
    :END:
    Queremos controlar la posición vertical $X$ de una masa, aplicando una fuerza \(u\) en esta. En la posición relajada, \(X=0, \; \dot{X} =0 \), la fuerza en el resorte es igual a la fuerza de gravedad.  
\[ m\ddot{X} = -kX - f\dot{X} + u\]
   *Actividad* Encuentra una representación del sistema en espacio de estados. 

   \begin{align*}
   \dot{x} &= A x + Bu\\ y &= Cx 
   \end{align*}


* Discretización                                                   :noexport:

** Discretización
   Solución general de un sistema lineal en espacio de estados 
   \begin{align*}
   x(t_k+\tau)& = \mathrm{e}^{A(\tau)} x(t_k) + \int_{0}^\tau \mathrm{e}^{As} B u\big((t_k+\tau)-s) ds
   \end{align*}
   
   #+begin_export latex
   \begin{center}
     \begin{tikzpicture}
       \draw[->] (-3,0) -- (6,0) node[below] {$t$};
       \draw (-2, 0.2) -- ( -2, 0) node[below] {$t_k=kh$};
       \draw (1, 0.2) -- ( 1, 0) node[below] {$t_{k+1}=kh+h$};
       \draw (4, 0.2) -- ( 4, 0) node[below] {$kh+2h$};
       \draw[thick, orange!90!black] (-3,0.3) -- (-2, 0.3) -- (-2,1) -- (1, 1) -- (1,0.8) -- (4, 0.8) --(4, 0.5) --(5.5, 0.5) node[pos=0.1, coordinate, pin=30:{$u(t)$}] {} ; 
       \draw[->] (-2, -0.7) -- (0, -0.7) node[below] {$\tau$};
     \end{tikzpicture}
   \end{center}
   #+end_export

   \begin{align*}
    x(kh+h) &= \mathrm{e}^{Ah} x(kh) + \int_{0}^{h} \mathrm{e}^{As} B u(kh+h-s) ds\\
     &= \underbrace{\mathrm{e}^{Ah}}_{\Phi(h)} x(kh) + \underbrace{\left(\int_{0}^h \mathrm{e}^{As} B ds \right)}_{\Gamma(h)} u(kh)
  \end{align*}

** Discretización - La exponencial de una matriz
   Matriz \(A\) cuadrada. Variable \(t\) escalar.
   \[ \mathrm{e}^{At} = 1 + At + \frac{t^2}{2!}A^2 + \frac{t^3}{3!} A^3 + \cdots\]
   Transformada de Laplace:
   \[ \laplace{\mathrm{e}^{At}} = (sI - A)^{-1}\]
   

** Discretización - ejemplo
   \begin{align*}
    x(kh+h) &= \mathrm{e}^{Ah} x(kh) + \int_{0}^{h} \mathrm{e}^{As} B u(kh+h-s) ds\\
     &= \underbrace{\mathrm{e}^{Ah}}_{\Phi(h)} x(kh) + \underbrace{\left(\int_{0}^h \mathrm{e}^{As} B ds \right)}_{\Gamma(h)} u(kh)
  \end{align*}
   \[ A = \begin{bmatrix} 0 & 0 & 0\\1 & 0 & 0\\0 & k_2 & 0\end{bmatrix}, \quad A^2 = \begin{bmatrix} 0 & 0 & 0\\1 & 0 & 0\\0 & k_2 & 0\end{bmatrix}\begin{bmatrix} 0 & 0 & 0\\1 & 0 & 0\\0 & k_2 & 0\end{bmatrix}= \begin{bmatrix} 0 & 0 & 0\\0 & 0 & 0\\k_2 & 0  & 0\end{bmatrix}, \quad A^3 = 0\]
   Entonces,
  \begin{align*}
   \Phi(h) &= \mathrm{e}^{Ah} = 1 + Ah + A^2 h^2/2  + \cdots \\
   &= \begin{bmatrix} 1 & 0 & 0\\0 & 1 & 0\\0 & 0 & 1\end{bmatrix} + \begin{bmatrix} 0 & 0 & 0\\1 & 0 & 0\\0 & k_2 & 0\end{bmatrix}h + \begin{bmatrix} 0 & 0 & 0\\0 & 0 & 0\\k_2 & 0 & 0\end{bmatrix}\frac{h^ 2}{2}= \begin{bmatrix} 1 & 0 & 0\\h & 1 & 0\\\frac{h^2k_2}{2} & hk_2 & 1\end{bmatrix}
   \end{align*}

** Discretización - ejemplo
   \begin{align*}
    x(kh+h) &= \mathrm{e}^{Ah} x(kh) + \int_{0}^{h} \mathrm{e}^{As} B u(kh+h-s) ds\\
     &= \underbrace{\mathrm{e}^{Ah}}_{\Phi(h)} x(kh) + \underbrace{\left(\int_{0}^h \mathrm{e}^{As} B ds \right)}_{\Gamma(h)} u(kh)
  \end{align*}
  \[\mathrm{e}^{As}B &=  \begin{bmatrix} 1 & 0 & 0\\h & 1 & 0\\\frac{s^2k_2}{2} & sk_2 & 1\end{bmatrix} \begin{bmatrix} k_1\\0\\0 \end{bmatrix} = k_1 \begin{bmatrix} 1\\s\\\frac{k_2s^2}{2} \end{bmatrix}
  \]
  \begin{align*}
  \Gamma (h) &= \int_0^h \mathrm{e}^{As}B ds = k_1 \int_0^h \begin{bmatrix} 1\\s\\\frac{k_2s^2}{2} \end{bmatrix}ds = k_1\begin{bmatrix} h\\ \frac{h^2}{2} \\ \frac{k_2 h^3}{6} \end{bmatrix} 
  \end{align*}

** Discretización - ejemplo
   \begin{align*}
    x(kh+h) &= \mathrm{e}^{Ah} x(kh) + \int_{0}^{h} \mathrm{e}^{As} B u(kh+h-s) ds\\
     &= \underbrace{\mathrm{e}^{Ah}}_{\Phi(h)} x(kh) + \underbrace{\left(\int_{0}^h \mathrm{e}^{As} B ds \right)}_{\Gamma(h)} u(kh)\\
     &= \begin{bmatrix} 1 & 0 & 0\\h & 1 & 0\\\frac{h^2k_2}{2} & hk_2 & 1\end{bmatrix} x(kh) + k_1 \begin{bmatrix} h\\ \frac{h^2}{2} \\ \frac{k_2 h^3}{6} \end{bmatrix} u(kh)
  \end{align*}

** Discretización - ejercicio
   *Actividad* Discretizar el sistema 
   \[ \dot(x) = Ax + Bu = \begin{bmatrix} 0 & 1\\ 0 & 0 \end{bmatrix} x + \begin{bmatrix}0\\1\end{bmatrix}\]


  

